package com.service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import org.springframework.stereotype.Service;

import com.entity.Customer;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;

@Service
public class PdfService {

public byte[] generatePdf(Customer customer) {

try {

Document document =
new Document(
PageSize.A4,
50,
50,
50,
50
);

ByteArrayOutputStream out =
new ByteArrayOutputStream();

PdfWriter.getInstance(
document,
out
);

document.open();


// =====================
// LOGO
// =====================

String logoPath =
"src/main/resources/static/logo.png";

Image logo =
Image.getInstance(
logoPath
);

logo.scaleToFit(
80,
80
);

logo.setAlignment(
Image.ALIGN_CENTER
);

document.add(
logo
);


// =====================
// TITLE
// =====================

Font title =
new Font(
Font.FontFamily.HELVETICA,
18,
Font.BOLD,
BaseColor.BLUE
);

Paragraph heading =
new Paragraph(
"UNION BANK OF INDIA",
title
);

heading.setAlignment(
Element.ALIGN_CENTER
);

document.add(
heading
);

document.add(
new Paragraph(
"FORM 121 CUSTOMER REPORT"
)
);

document.add(
new Paragraph(
" "
)
);


// =====================
// TABLE
// =====================

PdfPTable table =
new PdfPTable(2);

table.setWidthPercentage(
100
);

table.setSpacingBefore(
20
);

table.setWidths(
new int[]{
1,
2
}
);


// helper

addRow(
table,
"PAN Number",
customer.getPanNumber()
);

addRow(
table,
"Customer Name",
customer.getCustomerName()
);

addRow(
table,
"Age",
String.valueOf(
customer.getAge()
)
);

addRow(
table,
"Yearly Income",
"₹ "
+
customer.getYearlyIncome()
);

addRow(
table,
"Interest Income",
"₹ "
+
customer.getInterestIncome()
);

addRow(
table,
"Tax Regime",
customer.getRegime()
);

document.add(
table
);


// =====================
// FOOTER
// =====================

document.add(
new Paragraph(
"\n\n"
)
);

Paragraph footer =
new Paragraph(
"Generated On: "
+
LocalDateTime
.now()
.format(
DateTimeFormatter.ofPattern(
"dd-MM-yyyy HH:mm"
)
)
);

footer.setAlignment(
Element.ALIGN_RIGHT
);

document.add(
footer
);

document.add(
new Paragraph(
"\nGenerated by Union Bank Internal Portal"
)
);

document.close();

return out.toByteArray();

}

catch(Exception e) {

e.printStackTrace();

return null;

}

}


private void addRow(
PdfPTable table,
String key,
String value
){

Font bold =
new Font(
Font.FontFamily.HELVETICA,
12,
Font.BOLD
);

PdfPCell left =
new PdfPCell(
new Phrase(
key,
bold
)
);

PdfPCell right =
new PdfPCell(
new Phrase(
value
)
);

left.setPadding(10);
right.setPadding(10);

table.addCell(
left
);

table.addCell(
right
);

}

}